REMARK	NOMSG--GET RID OF UNMODIFIED COBOL MESSAGE

.EDIT 9991
.NAME BA
.DATE 06-JUL-82

.MODULE QCBL
.INSERT HLINI.+45,REPLACE,<HLRE @JB%CST>
	SETO	0,
.ENDI

.MODULE QCBLH
.INSERT HLINI.+45,REPLACE,<HLRE @JB%CST>
	SETO	0,
.ENDI
.ENDE
