R BATCH
RUN
Y
Y
APMEC.MAR
6584/6333
MIS-EDP
USING TITO 6250 BPI, PLEASE STORE THE FOLLOWING USER TO TAPE ONCE ONLY.

(APACCT:30)

PLEASE MAKE SOFTCOPY DIRECTORY TO (MISTAPE:38)APMEC.MAR
NO NEED FOR HARDCOPY DIR.

SEND MAIL TO (APACCT:30) AND (FRANK:38) AND (DUVALLC:38) WHEN DONE.
SEND TAPE(S) TO SOUTH BAY CENTER VIA INTER-OFFICE.
ATTN:CHRIS DUVALL MAIL STOP D31

