R BATCH
RUN
Y
Y
DPCEOM.MAR
6584/6333
MIS-EDP

USING TITO 6250 BPI, PLEASE STORE THE FOLLOWING DIRECTORY TO TAPE..

(DPACPROD:30)

STORE USER ONLY ONCE!

MAKE DIR TO (MISTAPE:38) DPCEOM.MAR

NO NEED TO MAKE HARD COPY DIR.


SEND MAIL TO (DPACPROD:30) ANN (FRANK:30) AND (DUVALLC:30).
DELIVER TAPE(S) TO SOUTH BAY CENTER VIA (INTER OFFICE-COURIER).
ATTN: CHRIS DUVALL. MAIL STOP: D31 THANKS-EDP.

