R BATCH
RUN
Y
Y
PRDNET.FEB
6584/6333
MIS-EDP


USING TITO 6250 BPI,PLEASE STORE THE FOLLOWING DIRECTORIES TO TAPE

(PRODNET:30)
(TESTEOM:30)
(DPACDEV:30)


STORE USER ONLY ONCE!

MAKE DIR TO (MISTAPE:38) PRDNET.FEB

NO NEED TO MAKE HARD COPY DIR.


SEND MAIL TO (PRODNET:30) AND (FRANK:30) AND (DUVALLC:30).
DELIVER TAPE(S) TO VALLEY GREEN DR. VIA (INTER OFFICE-COURIER).
ATTN: CHRIS DUVALL. MAIL STOP: VG1-B12 THANKS-EDP.


