R BATCH
RUN
Y
Y
PST940.NOV
6584/6333
MIS-EDP
USING TITO 6250 BPI,PLEASE STORE THE FOLLOWING DIRECTORY TO TAPE..

(OLD940:38)

STORE USER ONLY ONCE!

MAKE DIR TO (MISTAPE:38) PST940.NOV

NO NEED TO MAKE HARD COPY DIR. 


SEND MAIL TO (OLD940:38) AND (FRANK:38) AND (DUVALLC:38).
DELIVER TAPE(S) TO VALLEY GREEN DR. VIA (INTER OFFICE-COURIER).
ATTN: CHRIS DUVALL. MAIL STOP: VG1-B10 THANKS-EDP.


