R BATCH
RUN
Y
Y
TYMEOM.MAR
6584/6333
MIS-EDP

USING TITO 6250 BPI, PLEASE STORE THE FOLLOWING DIRECTORY TO TAPE..

(TYMUSEA:38)

STORE USER ONLY ONCE!

MAKE DIR TO (MISTAPE:38) TYMEOM.MAR

NO NEED TO MAKE HARD COPY DIR.


SEND MAIL TO (TYMUSEA:38) AND (FRANK:38) AND (DUVALLC:38).
DELIVER TAPE(S) TO SOUTH BAY CENTER VIA (INTER OFFICE-COURIER).
ATTN: CHRIS DUVALL. MAIL STOP: D31 THANKS-EDP.


