R BATCH
RUN
Y
Y
WECEOM.NOV
6584/6333
MIS-EDP

USING TITO 6250 BPI, PLEASE STORE THE FOLLOWING DIRECTORY TO TAPE..

(WECOACTG:38)
(WECOPROD:38)

STORE USERS ONLY ONCE!

MAKE DIR TO (MISTAPE:38) WECEOM.NOV

NO NEED TO MAKE HARD COPY DIR.


SEND MAIL TO (OLDPDP:38) AND (FRANK:38) AND (DUVALLC:38).
DELIVER TAPE(S) TO VALLEY GREEN DR. VIA (INTER OFFICE-COURIER).
ATTN: CHRIS DUVALL. MAIL STOP: VG1-B12 THANKS-EDP.


